#The default-src is the default policy for loading content such as JavaScript,
#Images, CSS, Font's, AJAX requests, Frames, HTML5 Media.
[default]
options = []                            # Options: 'self'
hosts = []                              # "*" can be used as wildcard


#Defines valid sources of JavaScript.
[scripts]
options = ["self", "inline", "eval"]    # Options: 'self', 'inline', 'eval'
hosts = ["https://google.com"]


#Defines valid sources for web wokers and nested browsing contexts loaded
#using elements such as <frame> and <iframe>
[frame]
options = ["self"]                      # Options: 'self'
hosts = []


#Applies to XMLHttpRequest (AJAX), WebSocket or EventSource.
#If not allowed the browser emulates a 400 HTTP status code.
[connect]
options = ["data"]                    # Available options: self
hosts = []
